[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
ink = { git = "https://github.com/use-ink/ink", branch = "cmichi-remove-wasm-default-to-revive" }
ink_env = { git = "https://github.com/use-ink/ink", branch = "cmichi-remove-wasm-default-to-revive" }
ink_metadata = { git = "https://github.com/use-ink/ink", branch = "cmichi-remove-wasm-default-to-revive" }

sp-core = { git = "https://github.com/paritytech/polkadot-sdk", rev = "645878a27115db52e5d63115699b4bbb89034067" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", rev = "645878a27115db52e5d63115699b4bbb89034067" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", rev = "645878a27115db52e5d63115699b4bbb89034067" }

# We want to reduce the size of build outputs in the CI to increase the effectiveness
# of the cache. Hence we need to apply some basic optimizations and disable everything
# that increases binary size.
[profile.debug-ci]
inherits = "dev"
opt-level = 1
incremental = false
debug = false
panic = "abort"
